.cargo/config.toml
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/setup.sh
.github/dependabot.yml
.github/workflows/base.yml
.gitignore
Cargo.toml
database/Cargo.toml
database/src/crate_info.rs
database/src/lib.rs
database/src/main.rs
database/src/quary_server.rs
database/src/tugraph_client.rs
database/tests/integration_test.rs
doc/database.md

- I configured the compilation and runtime environment of the project in devcontainer. It's still using TuGraph's image in the dockerfile and needs to wait a while for compilation. I will replace it with a compiled image if needed.
- I have set up the initial framework for crates-pro backend.
- The front-end client sends an HTTP request at `localhost:3000`, and the backend Server receives it and invocates the TuGraphClient.
- The usage doc is in doc/database.md.
- unit tests and integration tests are added as well.
- I added Github action workflow, which runs `cargo-check`, `cargo-clippy`, and `cargo doc`. (However, I'm not so sure Clippy's default lints are appropriate. )
- The environment in action is set up in docker `xizheyin/crates-pro`. It runs commands like `cargo check` directly …

Set up the environment, the database backend framework, the github actions.

---

import.config
model/src/crate_info.rs
repo_import/src/git.rs
repo_import/src/main.rs
repo_import/src/metadata_info.rs
repo_import/src/utils.rs

write edge into file, update edge import config. To be tested.

write edge into file, update edge import config

---

repo_import/src/main.rs
repo_import/src/metadata_info.rs
repo_import/src/version_info.rs

I tested it on top of 5000 repos and fix several bugs
including
1. additional performance overhead from using cargo_metadata
2. git2 as a C binding, which was unsafe and caused the program to terminate unexpectedly, I added extra checks.
3. strange dependency resolution failure
4. ...

fix bugs in git operation, testing for 5000 repos

---

import.config
model/src/crate_info.rs
repo_import/src/main.rs
repo_import/src/metadata_info.rs
repo_import/src/version_info.rs

fix bugs, finish tugraph data importing :)

---

Cargo.toml
src/main.rs
tests/integration_test.rs
tudriver/src/tugraph_client.rs

I added integration tests and the initial testing of the back-end functionality is now successful. It can successfully remove add get plugin information and call the plugin to get the result. During testing, I asked the plugin if accesskit_winit version 0.7.3 depends on accesskit version 0.8.1, and the plugin gave me "1", i.e. true. subsequently I will optimize the logic to accomplish more functions. So far, testing indicates that the current back-end logic and operation is relatively good. I think we can start designing the front end.

Fixed bugs, connected tugraph, added integration tests, initial testing successful.

---

Cargo.toml
crates_sync/src/consumer.rs
model/src/general_model.rs
model/src/lib.rs
model/src/plugin_model.rs
model/src/tugraph_model.rs
repo_import/Cargo.toml
repo_import/src/consumer.rs
repo_import/src/git.rs
repo_import/src/lib.rs
repo_import/src/version_info.rs
src/cli.rs
src/core_controller.rs
src/main.rs
tuplugins/plugin1/src/lib.rs
tuplugins/plugin2/src/lib.rs

I unified the logic of importing repos from initialization first to receiving a repo and parsing it one by one. But some bugs should be fixed.

Replace importing process from pg to MQ.

---

BUCK
tudriver/BUCK
tuplugins/BUCK

* Include build rules for `tudriver`
* Include build rules for `tuplugins/plugin1` and `tuplugins/plugin2`
* Include build rules for `crates-pro` (bin)

feat(build): Add Buck2 build rules

---

Cargo.toml
data_transporter/Cargo.toml
data_transporter/src/lib.rs
doc/database.md
repo_import/src/kafka_handler.rs
tudriver/src/tugraph_client.rs

Add Module data_transporter.

---

doc/Chinese.md
repo_import/src/crate_info.rs
repo_import/src/kafka_handler.rs
repo_import/src/lib.rs
repo_import/src/version_info.rs
src/core_controller.rs

Fix log for Debugging, fix Kafka rebalancing, fix memory exhaustion

---

doc/Chinese.md
repo_import/src/crate_info.rs
repo_import/src/lib.rs
repo_import/src/version_info.rs

Fix bug #65

---

repo_import/src/git.rs
repo_import/src/utils.rs
tudriver/src/tugraph_client.rs

Continue while parsing tree_id

---

doc/how-to-use-search.md
search/Cargo.toml
search/src/ai.rs
search/src/embedding.rs
search/src/lib.rs
search/src/search.rs
search/src/search_prepare.rs

This is a pull request for adding search module in crates pro.
It provides full-text search and AI chat functions. Please refer to how-to-use-search.md for instructions on how to use it. If there are any bugs while using it, please contact us for modification.

add search module

---

search/src/search.rs

modify search logic, due to the requirements of backend programmer, now search_crate return all the relevant crates, not just top n crates.Besides, reduce unnecessary SQL queries.

modify search logic

---

search/src/search.rs

change sort logic and handle null situations. 
fix bug #104

change sort logic

---

data_transporter/src/data_reader.rs
data_transporter/src/db.rs
data_transporter/src/lib.rs
data_transporter/src/route.rs

Expanded the CVE data, completed the new CVE analysis API and created routing for the dependepncy graph to complete the back-end API.

Build the API for CVE analysis and create graph routing

---

data_transporter/BUCK
data_transporter/src/handler.rs
data_transporter/src/lib.rs

add openapi-docs

---

.env
repo_import/src/lib.rs

Split the git repository into multiple folders by tag

Split the git repository into multiple folders by tag

---

analysis/BUCK
analysis/src/bin/analysis_tool_worker.rs
data_transporter/src/db.rs
data_transporter/src/handler.rs
data_transporter/src/lib.rs
deploy-analysis-tool-worker.sh

Add the function of displaying senseleak results in the data_transporter module

Add the function of displaying senseleak results in the data_transporter module

---

database/src/storage/github_handler_storage.rs
github-handler/src/contributor_analysis.rs
github-handler/src/main.rs

I fixed some bugs and cleaned up unnecessary code with specific changes:
1. Add query has_contributor_location to avoid dup run
2. Check if location exists before analyze a repo to improve performance
3. skip auth
4. clean code for modulizing
It requires a more refined modular design and decoupling.

enhance: improve performance and clean code

---

github-handler/src/config.rs
github-handler/src/services/github_api.rs

fix:add token polling logic

---

data_transporter/src/handler.rs
data_transporter/src/lib.rs
data_transporter/src/redis_store.rs

Including dependency, dependency_graph, dependent, version interface

Change the cache of all UI pages from pg to redis

---

data_transporter/src/db.rs
data_transporter/src/handler.rs
data_transporter/src/lib.rs

Backend code showing mirchecker execution results.

Display of mirchecker results
